name: CraftbookPipeSignExtender
author: Emcc13
description: Extending Craftbook Pipe Signs
version: 0.5
api-version: 1.18

main: com.github.Emcc13.CraftbookPipeCreator

commands:
  pipeadd:
    description: add item to pipe sign
  pipeinfo:
    description: get text of pipe sign
  pipeclear:
    description: remove text of pipe sign

permissions:
  pipeCreator:
    default: true
    description: allows command pipeadd